version: "3.8"

services:
  # Ride Matching Service
  ride-matching-service:
    build: .
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://rideshare:password@postgres:5432/rideshare_db
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=true
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app # For development hot reload
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rideshare_db
      - POSTGRES_USER=rideshare
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Redis Commander (GUI for Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  # pgAdmin (GUI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@rideshare.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
