apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-matching-service
  namespace: rideshare
spec:
  selector:
    matchLabels:
      app: ride-matching
  template:
    metadata:
      labels:
        app: ride-matching
    spec:
      containers:
        - name: ride-matching-service
          image: teleiosdupeacr01.azurecr.io/user-service:v1.0
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: ride-matching-secrets
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "150Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /api/rides/health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 20
